image: registry.gitlab.com/ultimaker/cura/cura-build-environment:centos7

stages:
  - build

build-and-test:
  stage: build
  script:
    - docker/build.sh
  artifacts:
    paths:
      - build

build-and-test_merge-requests:
  stage: build
  script:
    - docker/build.sh
  only:
    - merge_requests
